name: Basic commands
on:
schedule:
  - cron: "*/2 ****" #Every day at midnight UTC

jobs:
 demo-commands:
  runs-on:ubuntu-latest

  steps:
   - name: show current working directory
    run:Pwd

   - name: List files in the directory
    run:ls-la

   - name: print today's date
    run:date
    
